#!/usr/bin/perl 
   use File::Copy; 
   
   my $installPath = $ARGV[0]; 
   
   #the name that displays on the iPhone 
   my $bundleDisplayName = "New App"; 
   # prerendered icons don't have the glossy effect applied over them. 
   my $prerenderedIcon = 1; 
   # determines orientation of OS popups (text messages, volume controls) 
   my $landscapeOrientation = 0; 
   
   # these three are values defined in AppController.m 
   my $fpsRate = "60.0"; 
   my $accelerometerRate = "60.0"; 
   my $profilerOn = "0"; 
   
   #go through the info.plist file line by line until you find this one: 
   my $findLine = "CFBundleDisplayName"; 
   my $endOfPlist = "</dict>"; 
   
   #copy Default.png and Icon.png from Asset to installPath 
   my $iconFilename = "Icon.png"; 
   my $defaultFilename = "Default.png"; 
   
   # The type of player built: 
   # "dashboard", "standaloneWin32", "standaloneOSXIntel", "standaloneOSXPPC", "standaloneOSXUniversal", "webplayer", "iPhone" 
   my $target = $ARGV[1]; 
   
   print ("\n*** PostprocessBuildPlayer - Building at '$installPath' with target: $target ***\n"); 
   
   ################################################################ 
   # This modifies info.plist                                     # 
   ################################################################ 
   
   #open this file 
   
   $oplistPath = $installPath."/Info.plist"; 
   $nplistPath = $installPath."/Info.plist.tmp"; 
   
   open OLDPLIST, "<", $oplistPath or die("Cannot open Info.plist"); 
   open NEWPLIST, ">", $nplistPath or die("Cannot create new Info.plist");   
       
   while(<OLDPLIST>) 
   {
       
      ################################################################ 
      # Add any key/value pairs you want at the end of Info.plist    # 
      ################################################################ 
   
      if ($_ =~ m/$endOfPlist/) 
      { 
         my $keys = ""; 

         $keys .= "\t<key>UISupportedExternalAccessoryProtocols</key>\n";
         $keys .= "\t<array>\n";
         $keys .= "\t<string>com.orbotix.robotprotocol</string>\n";
         $keys .= "\t</array>\n";

         $_ = $keys . $_; 
      } 
       
      print NEWPLIST $_; 
   } 
   
   close OLDPLIST; 
   close NEWPLIST; 
   
   `mv \'$nplistPath\' \'$oplistPath\'`; 